<?php

//~ Template for list.php
// variables:
//  $title - page title
//  $status - status of Users to be displayed
//  $Users - Foc to be displayed

?>

<h1>
    <img src="img/status/<?php echo $status; ?>.png" alt="" title="<?php echo Utils::capitalize($status); ?>" class="icon" />
    <?php echo $title; ?>
</h1>

<?php if (empty($Users)): ?>
    <p>No items found.</p>
<?php else: ?>
    <ul class="list">
        <?php foreach ($Users as $Users): ?>
            <?php /* @var $Users foc */ ?>
            <?php $tooLate = $status == Users::STATUS_PENDING && $Users->getDueOn() < new DateTime(); ?>
            <li>
                <?php if ($tooLate): ?>
                    <img src="img/exclamation.png" alt="" title="Should be already done!" />
                <?php endif; ?>
                <img src="img/priority/<?php echo $Users->getPriority(); ?>.png" alt="Priority <?php echo $Users->getPriority(); ?>" title="Priority <?php echo $Users->getPriority(); ?>" />
                <h3><a href="<?php echo Utils::createLink('detail', array('id' => $Users->getId())) ?>"><?php echo Utils::escape($Users->getTitle()); ?></a></h3>
                <?php if ($Users->getDescription()): ?>
                    <p class="description"><?php echo Utils::escape($Users->getDescription()); ?></p>
                <?php endif; ?>
                <p><span class="label">Created On:</span> <?php echo Utils::escape(Utils::formatDateTime($Users->getCreatedOn())); ?></p>
                <p><span class="label">Due On:</span>
                    <?php if ($tooLate): ?><span class="too-late"><?php endif; ?>
                    <?php echo Utils::escape(Utils::formatDateTime($Users->getDueOn())); ?>
                    <?php if ($tooLate): ?></span><?php endif; ?>
                </p>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
